apiVersion: v1
kind: Service
metadata:
  name: restapi-service
spec:
  selector:
    app: restapi-app
  ports:
  - port: 2023
    targetPort: 2023
  type: LoadBalancer 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi-app 
  template:
    metadata:
      labels:
        app: restapi-app
    spec:
      containers:
      - name: restapi-app
        image: madhusudhan97/dataset-kubernetes:1.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 2023
